# Generated by Django 5.0 on 2023-12-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_ipaddress_article_ipaddress_user_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='user',
        ),
    ]
