# Generated by Django 5.0 on 2023-12-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_article_hits_article_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
