# Generated by Django 5.0 on 2024-04-14 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='article/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'], message='Video format must be mp4.'), django.core.validators.MaxValueValidator(31457280, message='Video size should not exceed 30 megabytes.')]),
        ),
    ]
