# Generated by Django 5.0 on 2024-01-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='adver_image')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'advertising',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=350)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('logo_site', models.ImageField(blank=True, null=True, upload_to='logo site')),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('pintrest', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('about_us', models.TextField()),
                ('copyright', models.CharField(max_length=800)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'setting',
            },
        ),
    ]
